/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import BUS.TacGiaBUS;
import DTO.TacGiaDTO;
import BUS.NCCBUS;
import DTO.NCCDTO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BUS.NXBBUS;
import DTO.NXBDTO;
import DTO.NhanVienDTO;
import java.text.SimpleDateFormat;

/**
 *
 * @author Admin
 */
public class CungCapGUI extends javax.swing.JPanel {
    /* Nhà Cung Cấp*/
     DefaultTableModel  modelncc = new DefaultTableModel();
    DefaultTableModel  tempncc = new DefaultTableModel();   
    NCCBUS BNCC = new NCCBUS();
    /*NHÀ XUẤT BẢN*/
    DefaultTableModel  modelnxb = new DefaultTableModel();
    DefaultTableModel  tempxb = new DefaultTableModel();
    NXBBUS BNXB = new NXBBUS();
    /*TÁC GIẢ*/
    public CungCapGUI() {
        initComponents();
    }
     public CungCapGUI(int width) {
        initComponents();
       this.setSize(width - 210, 950);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        pTacGia = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ComboBox = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btThemNCC = new javax.swing.JButton();
        btSuaNCC = new javax.swing.JButton();
        btXoaNCC = new javax.swing.JButton();
        lbMaNCC = new javax.swing.JLabel();
        txMaNCC = new javax.swing.JTextField();
        lbTenNCC = new javax.swing.JLabel();
        txTenNCC = new javax.swing.JTextField();
        lbDiachi = new javax.swing.JLabel();
        txDiaChi = new javax.swing.JTextField();
        lbThongBao = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbNCC = new javax.swing.JTable();
        btTimKiemNCC = new javax.swing.JButton();
        txTimKiem = new javax.swing.JTextField();
        cbTimKiemNCC = new javax.swing.JComboBox<>();
        btALLNCC = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbNXB = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txMaNXB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txSDT = new javax.swing.JTextField();
        txDiaChi1 = new javax.swing.JTextField();
        btThemNXB = new javax.swing.JButton();
        btXoaNXB = new javax.swing.JButton();
        btSuaNXB = new javax.swing.JButton();
        btAllNXB = new javax.swing.JButton();
        lbNXB = new javax.swing.JLabel();
        cbTimKiem1 = new javax.swing.JComboBox<>();
        lbTimkiem = new javax.swing.JLabel();
        txTimKiem1 = new javax.swing.JTextField();
        btTimKiem1 = new javax.swing.JButton();

        pTacGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Tác Giả", "Tên Tác Giả", "Địa Chỉ", "Số Điện Thoại" }));

        txtSearch.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jButton4.setText("Tìm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Tác Giả");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Thông Tin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã Tác Giả");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tên Tác Giả");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Địa Chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("SĐT:");

        txtMa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Tất Cả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTen))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua)
                    .addComponent(btnThem))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnXoa))
                .addContainerGap())
        );

        javax.swing.GroupLayout pTacGiaLayout = new javax.swing.GroupLayout(pTacGia);
        pTacGia.setLayout(pTacGiaLayout);
        pTacGiaLayout.setHorizontalGroup(
            pTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTacGiaLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pTacGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTacGiaLayout.setVerticalGroup(
            pTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTacGiaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTacGiaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 2));

        btThemNCC.setBackground(new java.awt.Color(153, 153, 153));
        btThemNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemNCC.setText("Thêm");
        btThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNCCActionPerformed(evt);
            }
        });

        btSuaNCC.setBackground(new java.awt.Color(153, 153, 153));
        btSuaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaNCC.setText("Sửa");
        btSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaNCCActionPerformed(evt);
            }
        });

        btXoaNCC.setBackground(new java.awt.Color(153, 153, 153));
        btXoaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaNCC.setText("Xóa");
        btXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaNCCActionPerformed(evt);
            }
        });

        lbMaNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaNCC.setText("Mã NCC:");

        txMaNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txMaNCCKeyPressed(evt);
            }
        });

        lbTenNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenNCC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenNCC.setText("Tên NCC:");

        txTenNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTenNCCKeyPressed(evt);
            }
        });

        lbDiachi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDiachi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDiachi.setText("Địa chỉ:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btThemNCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSuaNCC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoaNCC))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txTenNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(txDiaChi)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSuaNCC)
                    .addComponent(btXoaNCC)
                    .addComponent(btThemNCC))
                .addContainerGap())
        );

        lbThongBao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThongBao.setText("NHÀ CUNG CẤP");

        tbNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNCCMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbNCC);

        btTimKiemNCC.setBackground(new java.awt.Color(153, 153, 153));
        btTimKiemNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimKiemNCC.setText("Tìm");
        btTimKiemNCC.setActionCommand("Tìm ");
        btTimKiemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemNCCActionPerformed(evt);
            }
        });

        cbTimKiemNCC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbTimKiemNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NCC", "Tên NCC", "Địa chỉ" }));

        btALLNCC.setBackground(new java.awt.Color(153, 153, 153));
        btALLNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btALLNCC.setText("Tất Cả");
        btALLNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btALLNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btTimKiemNCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btALLNCC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbThongBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimKiemNCC)
                    .addComponent(txTimKiem)
                    .addComponent(cbTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btALLNCC))
                .addGap(146, 146, 146))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 204), 2));

        tbNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNXBMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbNXB);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mã NXB");

        txMaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMaNXBActionPerformed(evt);
            }
        });
        txMaNXB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txMaNXBKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tên:");

        txTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTenActionPerformed(evt);
            }
        });
        txTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txTenKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Địa chỉ:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("SDT:");

        txSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txDiaChi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txDiaChi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDiaChi1ActionPerformed(evt);
            }
        });
        txDiaChi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txDiaChi1KeyPressed(evt);
            }
        });

        btThemNXB.setBackground(new java.awt.Color(255, 255, 255));
        btThemNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThemNXB.setText("Thêm");
        btThemNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153), 2));
        btThemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemNXBActionPerformed(evt);
            }
        });

        btXoaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXoaNXB.setText("Xóa");
        btXoaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btXoaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaNXBActionPerformed(evt);
            }
        });

        btSuaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSuaNXB.setText("Sửa");
        btSuaNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 204)));
        btSuaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaNXBActionPerformed(evt);
            }
        });

        btAllNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAllNXB.setText("Tất Cả");
        btAllNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        btAllNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAllNXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btThemNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btXoaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSuaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btAllNXB)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThemNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbNXB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNXB.setText("Nhà Xuất Bản");

        cbTimKiem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã NXB", "Tên NXB", "Địa chỉ", "Số điện thoại" }));

        lbTimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTimkiem.setText("Tìm kiếm:");

        txTimKiem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btTimKiem1.setBackground(new java.awt.Color(255, 255, 255));
        btTimKiem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimKiem1.setText("Tìm kiếm");
        btTimKiem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 204), 2));
        btTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbTimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 11, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTimkiem)
                    .addComponent(cbTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimKiem1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int i = 0;
        txtMa.setText(model.getValueAt(index, i++).toString());
        txtTen.setText(model.getValueAt(index, i++).toString());
        txtDiaChi.setText(model.getValueAt(index, i++).toString());
        txtSDT.setText(model.getValueAt(index, i++).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try{
            TacGiaDTO tg = new TacGiaDTO();
            tg.setMaTG( txtMa.getText());
            tg.setTenTG(txtTen.getText());
            tg.setDiaChi(txtDiaChi.getText());
            tg.setSDT(txtSDT.getText());
            TacGiaBUS bus = new TacGiaBUS();
            bus.addTacGia(tg);
            docDSTG();

        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể thêm dữ liệu, vui lòng thử lại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try{
            TacGiaDTO tg = new TacGiaDTO();
            tg.setMaTG( txtMa.getText());
            tg.setTenTG(txtTen.getText());
            tg.setDiaChi(txtDiaChi.getText());
            tg.setSDT(txtSDT.getText());
            TacGiaBUS bus = new TacGiaBUS();
            bus.updateTacGia(tg);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể thay đổi dữ liệu, vui lòng thử lại");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try{
            TacGiaDTO tg = new TacGiaDTO();
            tg.setMaTG( txtMa.getText());
            tg.setTenTG(txtTen.getText());
            tg.setDiaChi(txtDiaChi.getText());
            tg.setSDT(txtSDT.getText());
            TacGiaBUS bus = new TacGiaBUS();
            bus.deleteTG(tg.getMaTG());
            docDSTG();
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể thay đổi dữ liệu, vui lòng thử lại");
        }
    }//GEN-LAST:event_btnXoaActionPerformed
      private void docDSTG(){
        try{
            Vector header = new Vector();
            header.add("Mã"); header.add("Tên"); header.add("Địa Chỉ"); header.add("SĐT"); 
            DefaultTableModel model = new DefaultTableModel(header, 0);
            TacGiaBUS bus = new TacGiaBUS();
            if(bus.getListTacGia() == null)
                bus.loadDSTacGia();
            for(TacGiaDTO TG : bus.getListTacGia()){
                Vector row = new Vector();
                row.add(TG.getMaTG());
                row.add(TG.getTenTG());
                row.add(TG.getDiaChi());
                row.add(TG.getSDT());
                model.addRow(row);
            }
            table.setModel(model);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Không thể đọc dữ liệu, vui lòng thử lại");
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        docDSTG();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index = ComboBox.getSelectedIndex();
        String search = txtSearch.getText();
        TacGiaBUS bus = new TacGiaBUS();
        /*  switch (index){
            case 0:
            docDSTG(bus.searchTacGia2(search, ":v", ":v", ":v"));
            break;
            case 1:
            docDSTG(bus.searchTacGia2(":v", search, ":v", ":v"));
            break;
            case 2:
            docDSTG(bus.searchTacGia2(":v", ":v", search, ":v"));
            break;
            case 3:
            docDSTG(bus.searchTacGia2(":v", ":v", ":v", search));
            break;
        }*/
    }//GEN-LAST:event_jButton4ActionPerformed
    /* NHÀ CUNG CẤP*/
     public void initNCC() throws Exception
    {
        while(modelncc.getRowCount()>0)
    	{
    		modelncc.removeRow(0);
    	}
        
    	tbNCC.removeAll();
        
        
        Vector header = new Vector();
        header.add("Mã NCC");
        header.add("Tên NCC");
        header.add("Địa chỉ");
        
        
        
        if (modelncc.getRowCount()==0)
        {
            modelncc=new DefaultTableModel(header,0);
        } 
        for (NCCDTO ncc: BNCC.list()) {
				 	
			        
            modelncc.addRow(addNCC(ncc));
        }
       
        tbNCC.setModel(modelncc);
        
    }
     private void ThemNCC(java.awt.event.ActionEvent evt) throws Exception {
	
         
            if(txMaNCC.getText().trim().compareTo("") != 0
               &&	txDiaChi.getText().trim().compareTo("") != 0
               &&	txTenNCC.getText().trim().compareTo("") != 0) {
                NCCDTO ncc=new NCCDTO();
                ncc.setMaNCC(txMaNCC.getText());
                ncc.setTenNCC(txTenNCC.getText());
                ncc.setDiaChi(txDiaChi.getText());
              
                BNCC.addNCC(ncc);

                modelncc.addRow(addNCC(ncc));
                tbNCC.setModel(modelncc);
          }
	 else JOptionPane.showMessageDialog(null,"Chưa điền đầy đủ thông kìa bạn ei!!!!", "thông báo",JOptionPane.INFORMATION_MESSAGE);
         
}
    public void XoaNCC() throws Exception{
	if(tbNCC.getModel() == modelncc)
            {
              int x = tbNCC.getSelectedRow();
              if (x>=0)
		{
		 NCCDTO ncc =new NCCDTO();
		 ncc = BNCC.list().get(x);
		 
		 
		 BNCC.deleteNCC(ncc.getMaNCC());
                
		 modelncc.removeRow(x);
		 tbNCC.setModel(modelncc);
                
		 }
             }
        else if(tbNCC.getModel() == tempncc)
        {
            int x = tbNCC.getSelectedRow();
              if (x>=0)
		{
		 
		
                 BNCC.deleteNCC(tbNCC.getValueAt(x, 0).toString());
                 tempncc.removeRow(x);
                 initNCC();
                 tbNCC.setModel(tempncc);
                }
        }
}
    private void SuaNCC(java.awt.event.ActionEvent evt) throws Exception {
		        
        int  i=tbNCC.getSelectedRow();        
        if(txMaNCC.getText().trim().compareTo("") != 0 
            &&	txTenNCC.getText().trim().compareTo("") != 0
            &&	txDiaChi.getText().trim().compareTo("") != 0) {
                    if(tbNCC.getModel() == modelncc)
			{
                            if (i>=0)
                            {
                                NCCDTO ncc=new NCCDTO();
				
                                ncc.setMaNCC(BNCC.list().get(i).getMaNCC());
				ncc.setTenNCC(txTenNCC.getText());
				ncc.setDiaChi(txDiaChi.getText());
                                
                               
                               
                                BNCC.updateNCC(ncc);
                                initNCC();        
                            }
                        }
                    else if(tbNCC.getModel() == tempncc)
                    {
                        int x = tbNCC.getSelectedRow();
                          if (x>=0)
                            {
                             NCCDTO ncc=new NCCDTO();
                             ncc.setMaNCC(tbNCC.getValueAt(x, 0).toString());
                             ncc.setTenNCC(txTenNCC.getText());
                             ncc.setDiaChi(txDiaChi.getText());
                             
                             
                             BNCC.updateNCC(ncc);
                             tempncc.setValueAt(ncc.getTenNCC(), x, 1);
                             tempncc.setValueAt(ncc.getDiaChi(), x, 2);
                            
                             initNCC();
                             tbNCC.setModel(tempncc);
                            }
                    }
        
    }
    else JOptionPane.showMessageDialog(null,"Chưa điền đầy đủ thông kìa bạn ei!!!!", "thông báo",JOptionPane.INFORMATION_MESSAGE);
        
}
    private void show(java.awt.event.MouseEvent evt) throws Exception {
        int  i=tbNCC.getSelectedRow();
        
       if(tbNCC.getModel() == modelncc)
       {
	       if(i>=0)
	       {
	           NCCDTO ncc =new NCCDTO();
	           ncc=BNCC.list().get(i);
	           txMaNCC.setText(ncc.getMaNCC());
	           txDiaChi.setText(ncc.getDiaChi());
	           txTenNCC.setText(ncc.getTenNCC());
	       }
       }
       else if(tbNCC.getModel() == tempncc)
       {
           txMaNCC.setText(tbNCC.getValueAt(i, 0).toString());
           txTenNCC.setText(tbNCC.getValueAt(i, 1).toString());
           txDiaChi.setText(tbNCC.getValueAt(i, 2).toString());
       }
       
   }
    private void search() throws Exception
    {
    	   
    	    while(tempncc.getRowCount()>0)
    	    {
    	    	tempncc.removeRow(0);
    	    }
            Vector header = new Vector();
	        header.add("Mã NCC");
	        header.add("Tên NCC");
	        header.add("Địa chỉ");
	        

            if (tempncc.getRowCount()==0)
                        { tempncc=new DefaultTableModel(header,0);} 


            if(cbTimKiemNCC.getSelectedItem() == "Mã NCC" )
            {
                    NCCDTO ncc = BNCC.timkiem_MaNCC(txTimKiem.getText());			    			
                    tempncc.addRow(addNCC(ncc));

            }		 

            if(cbTimKiemNCC.getSelectedItem() == "Tên NCC" )
            {
                    for(NCCDTO ncc : BNCC.timkiem_TenNCC(txTimKiem.getText()))
                    {
                            tempncc.addRow(addNCC(ncc));

                    }
            }
            if(cbTimKiemNCC.getSelectedItem() == "Địa chỉ" )
            {
                    for(NCCDTO ncc : BNCC.timkiem_DiaChi(txTimKiem.getText()))
                    {
                            tempncc.addRow(addNCC(ncc));

                    }
            }	
            if(tbNCC.getModel() == modelncc)
            tbNCC.removeAll();
            tbNCC.setModel(tempncc);   	
    }      
    
    private Vector addNCC(NCCDTO ncc)
    {
        Vector row=new Vector();
        row.add(ncc.getMaNCC());
        row.add(ncc.getTenNCC());
        row.add(ncc.getDiaChi());
        return row;
    }
    private void btThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNCCActionPerformed
        try {
            ThemNCC(evt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }

    }//GEN-LAST:event_btThemNCCActionPerformed

    private void btSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaNCCActionPerformed
        try {
            SuaNCC(evt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thể sửa NCC này");
        }
    }//GEN-LAST:event_btSuaNCCActionPerformed

    private void btXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaNCCActionPerformed
        try {
            XoaNCC();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_btXoaNCCActionPerformed

    private void txMaNCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMaNCCKeyPressed
        if(evt.getKeyCode() == 10)
        {
            txTenNCC.requestFocus();
        }
    }//GEN-LAST:event_txMaNCCKeyPressed

    private void txTenNCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTenNCCKeyPressed
        if(evt.getKeyCode() == 10)
        {
            txDiaChi.requestFocus();
        }
    }//GEN-LAST:event_txTenNCCKeyPressed

    private void tbNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNCCMouseClicked
        try {
            show(evt);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tbNCCMouseClicked

    private void btTimKiemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemNCCActionPerformed
        try {
            search();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả");
        }

    }//GEN-LAST:event_btTimKiemNCCActionPerformed

    private void btALLNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btALLNCCActionPerformed
        if(tbNCC.getModel() == tempncc)
        {
            tbNCC.removeAll();
            tbNCC.setModel(modelncc);
        }
    }//GEN-LAST:event_btALLNCCActionPerformed

    private void tbNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNXBMouseClicked
        try {
            show(evt);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tbNXBMouseClicked

    private void txMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMaNXBActionPerformed

    private void txMaNXBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txMaNXBKeyPressed
        if(evt.getKeyCode() == 10)
        {
            txTen.requestFocus();
        }
    }//GEN-LAST:event_txMaNXBKeyPressed

    private void txTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTenActionPerformed

    }//GEN-LAST:event_txTenActionPerformed

    private void txTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txTenKeyPressed
        if(evt.getKeyCode() == 10)
        {
            txDiaChi.requestFocus();
        }
    }//GEN-LAST:event_txTenKeyPressed

    private void txDiaChi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDiaChi1ActionPerformed

    }//GEN-LAST:event_txDiaChi1ActionPerformed

    private void txDiaChi1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txDiaChi1KeyPressed
        if(evt.getKeyCode() == 10)
        {
            txSDT.requestFocus();
        }
    }//GEN-LAST:event_txDiaChi1KeyPressed
    public void initNXB() throws Exception
    {
        while(modelnxb.getRowCount()>0)
    	{
    		modelnxb.removeRow(0);
    	}
        
    	tbNXB.removeAll();
        
        
        Vector header = new Vector();
        header.add("Mã NXB");
        header.add("Tên NXB");
        header.add("Địa chỉ");
        header.add("Số điện thoại");
        
        
        if (modelnxb.getRowCount()==0)
        {
            modelnxb=new DefaultTableModel(header,0);
        } 
        for (NXBDTO nxb: BNXB.list()) {
				 	
			        
            modelnxb.addRow(addNXB(nxb));
        }
       
        tbNXB.setModel(modelnxb);
        
    }
    
    
    private void ThemNXB(java.awt.event.ActionEvent evt) throws Exception {
	
         
            if(txMaNXB.getText().trim().compareTo("") != 0
               &&	txDiaChi.getText().trim().compareTo("") != 0
               &&	txTen.getText().trim().compareTo("") != 0
               &&	txSDT.getText().trim().compareTo("") != 0) {
           NXBDTO nxb=new NXBDTO();
           nxb.setMaNXB(txMaNXB.getText());
           nxb.setTenNXB(txTen.getText());
           nxb.setDiaChi(txDiaChi.getText());
           nxb.setSDT(txSDT.getText());
           
           BNXB.addNXB(nxb);
           
           modelnxb.addRow(addNXB(nxb));
           tbNXB.setModel(modelnxb);
          }
	 else JOptionPane.showMessageDialog(null,"Chưa điền đầy đủ thông kìa bạn ei!!!!", "thông báo",JOptionPane.INFORMATION_MESSAGE);
         
}
    public void XoaNXB() throws Exception{
	if(tbNXB.getModel() == modelnxb)
            {
              int x = tbNXB.getSelectedRow();
              if (x>=0)
		{
		 NXBDTO nxb =new NXBDTO();
		 nxb = BNXB.list().get(x);
		 
		 
		 BNXB.deleteNXB(nxb.getMaNXB());
                
		 modelnxb.removeRow(x);
		 tbNXB.setModel(modelnxb);
                
		 }
             }
        else if(tbNXB.getModel() == tempxb)
        {
            int x = tbNXB.getSelectedRow();
              if (x>=0)
		{
		 
		
                 BNXB.deleteNXB(tbNXB.getValueAt(x, 0).toString());
                 tempxb.removeRow(x);
                 initNXB();
                 tbNXB.setModel(tempxb);
                }
        }
}
    private void SuaNXB(java.awt.event.ActionEvent evt) throws Exception {
		        
        int  i=tbNXB.getSelectedRow();        
        if(txMaNXB.getText().trim().compareTo("") != 0 
            &&	txTen.getText().trim().compareTo("") != 0
            &&	txDiaChi.getText().trim().compareTo("") != 0
            &&	txSDT.getText().trim().compareTo("") != 0) {
                    if(tbNXB.getModel() == modelnxb)
			{
                            if (i>=0)
                            {
                                NXBDTO nxb=new NXBDTO();
				
                                nxb.setMaNXB(BNXB.list().get(i).getMaNXB());
				nxb.setTenNXB(txTen.getText());
				nxb.setDiaChi(txDiaChi.getText());
                                nxb.setSDT(txSDT.getText());
                               
                               
                                BNXB.updateNXB(nxb);
                                initNXB();        
                            }
                        }
                    else if(tbNXB.getModel() == tempxb)
                    {
                        int x = tbNXB.getSelectedRow();
                          if (x>=0)
                            {
                             NXBDTO nxb=new NXBDTO();
                             nxb.setMaNXB(tbNXB.getValueAt(x, 0).toString());
                             nxb.setTenNXB(txTen.getText());
                             nxb.setDiaChi(txDiaChi.getText());
                             nxb.setSDT(txSDT.getText());
                             
                             BNXB.updateNXB(nxb);
                             tempxb.setValueAt(nxb.getTenNXB(), x, 1);
                             tempxb.setValueAt(nxb.getDiaChi(), x, 2);
                             tempxb.setValueAt(nxb.getSDT(), x, 3);
                             initNXB();
                             tbNXB.setModel(tempxb);
                            }
                    }
        
    }
    else JOptionPane.showMessageDialog(null,"Chưa điền đầy đủ thông kìa bạn ei!!!!", "thông báo",JOptionPane.INFORMATION_MESSAGE);
        
}
    private void showNXB(java.awt.event.MouseEvent evt) throws Exception {
        int  i=tbNXB.getSelectedRow();
        
       if(tbNXB.getModel() == modelnxb)
       {
	       if(i>=0)
	       {
	           NXBDTO nxb =new NXBDTO();
	           nxb=BNXB.list().get(i);
	           txMaNXB.setText(nxb.getMaNXB());
	           txDiaChi.setText(nxb.getDiaChi());
	           txTen.setText(nxb.getTenNXB());
	           txSDT.setText(nxb.getSDT());
	           
                   
	       }
       }
       else if(tbNXB.getModel() == tempxb)
       {
           txMaNXB.setText(tbNXB.getValueAt(i, 0).toString());
           txTen.setText(tbNXB.getValueAt(i, 1).toString());
           txDiaChi.setText(tbNXB.getValueAt(i, 2).toString());
           txSDT.setText(tbNXB.getValueAt(i, 3).toString());
           
       }
       
   }
    private void searchNXB() throws Exception
    {
    	   
    	    while(tempxb.getRowCount()>0)
    	    {
    	    	tempxb.removeRow(0);
    	    }
            Vector header = new Vector();
	        header.add("Mã NXB");
	        header.add("Tên NXB");
	        header.add("Địa chỉ");
	        header.add("Số điện thoại");
	        
	        if (tempxb.getRowCount()==0)
	                    { tempxb=new DefaultTableModel(header,0);} 
	       
	        
	        if(cbTimKiem1.getSelectedItem() == "Mã NXB" )
    		{
	        	NXBDTO nxb = BNXB.timkiem_MaNXB(txTimKiem.getText());			    			
                        tempxb.addRow(addNXB(nxb));
                       
    		}		 
	    		
	    	if(cbTimKiem1.getSelectedItem() == "Tên NXB" )
                {
                        for(NXBDTO nxb : BNXB.timkiem_TenNXB(txTimKiem.getText()))
                        {
                                tempxb.addRow(addNXB(nxb));
                               
                        }
                }
	    	if(cbTimKiem1.getSelectedItem() == "Địa chỉ" )
                {
                        for(NXBDTO nxb : BNXB.timkiem_DiaChiNXB(txTimKiem.getText()))
                        {
                                tempxb.addRow(addNXB(nxb));
                                
                        }
                }
                
                if(cbTimKiem1.getSelectedItem() == "Số điện thoại" )
                {
                        for(NXBDTO nxb : BNXB.timkiem_SDT(txTimKiem.getText()))
                        {
                                tempxb.addRow(addNXB(nxb));
                                
                        }
                }
      		
            if(tbNXB.getModel() == modelnxb)
            tbNXB.removeAll();
            tbNXB.setModel(tempxb);   	
    }      
    
    private Vector addNXB(NXBDTO nxb)
    {
    		Vector row=new Vector();
	        row.add(nxb.getMaNXB());
	        row.add(nxb.getTenNXB());
	        row.add(nxb.getDiaChi());
	        row.add(nxb.getSDT());
	       
	        return row;

    }
    private void btThemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemNXBActionPerformed
        try {
            ThemNXB(evt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thể thêm NXB này");
        }
    }//GEN-LAST:event_btThemNXBActionPerformed

    private void btXoaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaNXBActionPerformed
        try {
            XoaNXB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thể xóa NXB này");
        }
    }//GEN-LAST:event_btXoaNXBActionPerformed

    private void btSuaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaNXBActionPerformed
        try {
            SuaNXB(evt);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không thể sửa NXB này");
        }
    }//GEN-LAST:event_btSuaNXBActionPerformed

    private void btAllNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAllNXBActionPerformed
        if(tbNXB.getModel() == tempxb)
        {
            tbNXB.removeAll();
            tbNXB.setModel(modelnxb);
        }
    }//GEN-LAST:event_btAllNXBActionPerformed

    private void btTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiem1ActionPerformed
        try {
            searchNXB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy kết quả");
        }
    }//GEN-LAST:event_btTimKiem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton btALLNCC;
    private javax.swing.JButton btAllNXB;
    private javax.swing.JButton btSuaNCC;
    private javax.swing.JButton btSuaNXB;
    private javax.swing.JButton btThemNCC;
    private javax.swing.JButton btThemNXB;
    private javax.swing.JButton btTimKiem1;
    private javax.swing.JButton btTimKiemNCC;
    private javax.swing.JButton btXoaNCC;
    private javax.swing.JButton btXoaNXB;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTimKiem1;
    private javax.swing.JComboBox<String> cbTimKiemNCC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbDiachi;
    private javax.swing.JLabel lbMaNCC;
    private javax.swing.JLabel lbNXB;
    private javax.swing.JLabel lbTenNCC;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JLabel lbTimkiem;
    private javax.swing.JPanel pTacGia;
    private javax.swing.JTable table;
    private javax.swing.JTable tbNCC;
    private javax.swing.JTable tbNXB;
    private javax.swing.JTextField txDiaChi;
    private javax.swing.JTextField txDiaChi1;
    private javax.swing.JTextField txMaNCC;
    private javax.swing.JTextField txMaNXB;
    private javax.swing.JTextField txSDT;
    private javax.swing.JTextField txTen;
    private javax.swing.JTextField txTenNCC;
    private javax.swing.JTextField txTimKiem;
    private javax.swing.JTextField txTimKiem1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
