/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.KhachHangBUS;
import DTO.KhachHangDTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.awt.print.*;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.FormulaEvaluator;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author tungk
 */
public class KhachHangGUI extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangGUI
     */
    DefaultTableModel model = new DefaultTableModel();
    KhachHangBUS bus = new KhachHangBUS();
    
    public KhachHangGUI(int width) {
        initComponents();
        docDSKH();
        dropdown.setSelectedIndex(0);
        textAmount.setText(String.valueOf(model.getRowCount()));
        setSize(width - 250, 720);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phaiGroup = new javax.swing.ButtonGroup();
        optionGroup = new javax.swing.ButtonGroup();
        header = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        controls = new javax.swing.JPanel();
        lbMa = new javax.swing.JLabel();
        lbHo = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbSdt = new javax.swing.JLabel();
        lbPhai = new javax.swing.JLabel();
        lbTct = new javax.swing.JLabel();
        lbNgaySinh = new javax.swing.JLabel();
        pnTimKiem = new javax.swing.JPanel();
        dropdown = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        option1 = new javax.swing.JRadioButton();
        option2 = new javax.swing.JRadioButton();
        input = new javax.swing.JTextField();
        textMa = new javax.swing.JTextField();
        textHo = new javax.swing.JTextField();
        textTen = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textSdt = new javax.swing.JTextField();
        textTct = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        btnRefresh = new javax.swing.JButton();
        dateChoser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        textAmount = new javax.swing.JTextField();
        btnReport = new javax.swing.JButton();
        btnDocXLS = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        header.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(0, 204, 204));
        header.setText("THÔNG TIN KHÁCH HÀNG");

        jScrollPane1.setHorizontalScrollBar(null);

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        controls.setBackground(new java.awt.Color(255, 255, 255));
        controls.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2), "NHẬP THÔNG TIN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        lbMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMa.setText("Mã KH");

        lbHo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbHo.setText("Họ");

        lbTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTen.setText("Tên");

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail.setText("Email");

        lbSdt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSdt.setText("SĐT");

        lbPhai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPhai.setText("Phái");

        lbTct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTct.setText("Tổng Chi:");

        lbNgaySinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNgaySinh.setText("Ngày sinh");

        pnTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true), "TÌM KIẾM", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        dropdown.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Khách Hàng", "Họ", "Tên", "Số Điện Thoại", "Email", "Phái", "Tổng Chi Tiêu" }));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(153, 255, 153));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        option1.setBackground(new java.awt.Color(255, 255, 255));
        optionGroup.add(option1);
        option1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        option1.setText("Nam");

        option2.setBackground(new java.awt.Color(255, 255, 255));
        optionGroup.add(option2);
        option2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        option2.setText("Nữ");
        option2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option2ActionPerformed(evt);
            }
        });

        input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnTimKiem)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemLayout.createSequentialGroup()
                        .addComponent(option1)
                        .addGap(18, 18, 18)
                        .addComponent(option2)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemLayout.createSequentialGroup()
                        .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(input)
                            .addComponent(dropdown, 0, 246, Short.MAX_VALUE))
                        .addGap(43, 43, 43))))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(option1)
                    .addComponent(option2))
                .addGap(18, 18, 18)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnTimKiem)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        textMa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textHo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textTen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textSdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        textTct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnThem.setBackground(new java.awt.Color(0, 102, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_30px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(204, 0, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_forever_30px_1.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 204, 204));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 0, 204));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_maintenance_30px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        radioNam.setBackground(new java.awt.Color(255, 255, 255));
        phaiGroup.add(radioNam);
        radioNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioNam.setText("Nam");
        radioNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNamActionPerformed(evt);
            }
        });

        radioNu.setBackground(new java.awt.Color(255, 255, 255));
        phaiGroup.add(radioNu);
        radioNu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radioNu.setText("Nữ");

        btnRefresh.setBackground(new java.awt.Color(255, 153, 0));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        btnRefresh.setText("LÀM MỚI");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlsLayout = new javax.swing.GroupLayout(controls);
        controls.setLayout(controlsLayout);
        controlsLayout.setHorizontalGroup(
            controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsLayout.createSequentialGroup()
                        .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEmail)
                            .addComponent(lbSdt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(controlsLayout.createSequentialGroup()
                        .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(controlsLayout.createSequentialGroup()
                                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMa)
                                    .addComponent(lbHo)
                                    .addComponent(lbTen))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textTen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textHo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(controlsLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa)
                                .addGap(9, 9, 9)))
                        .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(controlsLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnSua)
                                .addGap(32, 32, 32)
                                .addComponent(btnRefresh))
                            .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(controlsLayout.createSequentialGroup()
                                    .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTct)
                                        .addComponent(lbPhai))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textTct, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(controlsLayout.createSequentialGroup()
                                            .addComponent(radioNam, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(radioNu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(controlsLayout.createSequentialGroup()
                                    .addComponent(lbNgaySinh)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateChoser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        controlsLayout.setVerticalGroup(
            controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMa)
                    .addComponent(lbPhai)
                    .addComponent(textMa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNam)
                    .addComponent(radioNu))
                .addGap(10, 10, 10)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHo)
                    .addComponent(lbTct)
                    .addComponent(textHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTen)
                        .addComponent(lbNgaySinh)
                        .addComponent(textTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChoser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmail)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSdt)
                    .addComponent(textSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(controlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem)))
            .addGroup(controlsLayout.createSequentialGroup()
                .addComponent(pnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Số lượng khách hàng:");

        textAmount.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        textAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textAmount.setEnabled(false);
        textAmount.setFocusable(false);
        textAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAmountActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(255, 204, 102));
        btnReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ms_excel_30px.png"))); // NOI18N
        btnReport.setText("Xuất Excel");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnDocXLS.setBackground(new java.awt.Color(153, 255, 153));
        btnDocXLS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDocXLS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ms_excel_30px.png"))); // NOI18N
        btnDocXLS.setText("Nhập Excel");
        btnDocXLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocXLSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(header)
                .addGap(293, 293, 293))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocXLS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDocXLS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(header)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void radioNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try{
        String ma = textMa.getText();
        String ho = textHo.getText();
        String ten = textTen.getText();
        String sdt = textSdt.getText();
        String email = textEmail.getText();
        int tct = Integer.parseInt(textTct.getText());
        
        Date date = dateChoser.getDate();
        
        int ngay = date.getDate();
        int thang = date.getMonth() + 1;
        int nam = date.getYear() + 1900;
        String ngaysinh = nam + "-" + thang + "-" + ngay;
        
        KhachHangDTO kh = new KhachHangDTO(ma, ho, ten, sdt, email, radioNam.isSelected(), tct);
        kh.setNgaySinh(ngaysinh);
        
        
        bus.them(kh);
        docDSKH();
        textAmount.setText(String.valueOf(model.getRowCount()));
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập lại");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        int i = 0;
        textMa.setText(model.getValueAt(index, i++).toString());
        textHo.setText(model.getValueAt(index, i++).toString());
        textTen.setText(model.getValueAt(index, i++).toString());
        textSdt.setText(model.getValueAt(index, i++).toString());
        textEmail.setText(model.getValueAt(index, i++).toString());
        if(model.getValueAt(index, i++).toString().equals("nam"))
            radioNam.setSelected(true);
        else radioNu.setSelected(true);
        textTct.setText(model.getValueAt(index, i++).toString());
        String[] date = model.getValueAt(index, i++).toString().split("-", 3);
        Date selected = new Date(Integer.parseInt(date[0]) - 1900, Integer.parseInt(date[1]) - 1, Integer.parseInt(date[2]));
        dateChoser.setDate(selected);
    }//GEN-LAST:event_tableMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String id = textMa.getText();
        String ho = textHo.getText();
        String ten = textTen.getText();
        String sdt = textSdt.getText();
        String email = textEmail.getText();
        boolean phai = radioNam.isSelected();
        int tct = Integer.parseInt( (textTct.getText()) );
        
        Date date = dateChoser.getDate();
        
        int ngay = date.getDate();
        int thang = date.getMonth() + 1;
        int nam = date.getYear() + 1900;
        String ngaysinh = nam + "-" + thang + "-" + ngay;
        KhachHangDTO kh = new KhachHangDTO(id, ho, ten, sdt, email, phai, tct);
        kh.setNgaySinh(ngaysinh);
        
        bus.xoa(kh);
        docDSKH();
        textAmount.setText(String.valueOf(model.getRowCount()));
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int index = table.getSelectedRow();
        String id = textMa.getText();
        String ho = textHo.getText();
        String ten = textTen.getText();
        String sdt = textSdt.getText();
        String email = textEmail.getText();
        boolean phai = radioNam.isSelected();
        int tct = Integer.parseInt( (textTct.getText()) );
        
        Date date = dateChoser.getDate();
        
        int ngay = date.getDate();
        int thang = date.getMonth() + 1;
        int nam = date.getYear() + 1900;
        String ngaysinh = nam + "-" + thang + "-" + ngay;
        KhachHangDTO kh = new KhachHangDTO(id, ho, ten, sdt, email, phai, tct);
        kh.setNgaySinh(ngaysinh);
        
        bus.sua(kh);
        docDSKH();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:
        int index = dropdown.getSelectedIndex();
        switch(index){
            case 5:
                option1.setEnabled(true);
                option2.setEnabled(true);
                input.setEnabled(false);
                break;
            case 6:
                option1.setEnabled(true);
                option1.setText("Lớn Hơn");
                
                option2.setEnabled(true);
                option2.setText("Nhỏ Hơn");
                
                input.setEnabled(true);
                break;
            default:
                input.setEnabled(true);
                option1.setEnabled(false);
                option2.setEnabled(false);
        }
    }//GEN-LAST:event_dropdownActionPerformed

    private void option2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_option2ActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        int index = dropdown.getSelectedIndex();
        String in = input.getText();
        boolean isNu = option1.isSelected();
        switch(index){
            case(0):
                table.setModel(ketQuaTimKiem(bus.timKiemId(in)));
                break;
            case(1):
                table.setModel(ketQuaTimKiem(bus.timKiemHo(in)));
                break;
            case(2):
                table.setModel(ketQuaTimKiem(bus.timKiemTen(in)));
                break;
            case(3):
                table.setModel(ketQuaTimKiem(bus.timKiemSDT(in)));
                break;
            case(4):
                table.setModel(ketQuaTimKiem(bus.timKiemEmail(in)));
                break;
            case(5):
                table.setModel(ketQuaTimKiem(bus.timKiemPhai(isNu)));
                break;
            case(6):
                table.setModel(ketQuaTimKiem(bus.timKiemTCT(isNu, Integer.parseInt(in))));
                break;
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        docDSKH();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void textAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAmountActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        try{
            table.print(JTable.PrintMode.FIT_WIDTH);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Không thể in PDF");
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnDocXLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocXLSActionPerformed
        // TODO add your handling code here:
        //obtaining input bytes from a file
        try{
            JFileChooser chooser = new JFileChooser();
            int rVal = chooser.showOpenDialog(null);
            String path = "";
            if(rVal == JFileChooser.APPROVE_OPTION){
                path = chooser.getCurrentDirectory().toString() + "\\" + chooser.getSelectedFile().getName();
            }
            
            FileInputStream fis=new FileInputStream(new File( path ));  
            //creating workbook instance that refers to .xls file  
            Workbook wb=new HSSFWorkbook(fis);   
            //creating a Sheet object to retrieve the object  
            Sheet sheet=wb.getSheetAt(0);  
            //evaluating cell type   
            FormulaEvaluator formulaEvaluator=wb.getCreationHelper().createFormulaEvaluator();  
            KhachHangBUS bus = new KhachHangBUS();
            for(Row row: sheet)     //iteration over row using for each loop  
            {  
                KhachHangDTO khachhang = new KhachHangDTO();
                int i = 0;
                khachhang.setId(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                khachhang.setHo(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                khachhang.setTen(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                khachhang.setSdt(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                khachhang.setEmail(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                khachhang.setPhai(row.getCell(i++).getStringCellValue()=="Nữ"?false:true);
                System.out.print(i + " ");
                khachhang.setTct( (int)row.getCell(i++).getNumericCellValue() );
                System.out.print(i + " ");
                khachhang.setNgaySinh(row.getCell(i++).getStringCellValue());
                System.out.print(i + " ");
                bus.them(khachhang);
            }  
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Lỗi nhập excel!");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnDocXLSActionPerformed

    private void docDSKH(){
        if(bus.dskh == null) bus.docDSKH();
        Vector<String> header = new Vector();
        //model HEADER
        header.add("Mã KH"); header.add("Họ KH"); header.add("Tên KH"); header.add("SĐT");
        header.add("Email"); header.add("Phái"); header.add("Tổng chi"); header.add("Ngày Sinh"); 
        model = new DefaultTableModel(header, 0);
        
        for(KhachHangDTO kh : bus.dskh){
            Vector row = new Vector();
            row.add(kh.getId());
            row.add(kh.getHo());
            row.add(kh.getTen());
            row.add(kh.getSdt());
            row.add(kh.getEmail());
            row.add(!kh.isPhai()?"nữ":"nam");
            row.add(kh.getTct());
            row.add(kh.getNgaySinh());
            model.addRow(row);
        }
        
        table.setModel(model);
    }

    private DefaultTableModel ketQuaTimKiem(ArrayList<KhachHangDTO> rs){
        Vector<String> header = new Vector();
        //model HEADER
        header.add("Mã KH"); header.add("Họ KH"); header.add("Tên KH"); header.add("SĐT");
        header.add("Email"); header.add("Phái"); header.add("Tổng chi"); header.add("Ngày Sinh"); 
        model = new DefaultTableModel(header, 0);
        
        for(KhachHangDTO kh : rs){
            Vector row = new Vector();
            row.add(kh.getId());
            row.add(kh.getHo());
            row.add(kh.getTen());
            row.add(kh.getSdt());
            row.add(kh.getEmail());
            row.add(!kh.isPhai()?"nữ":"nam");
            row.add(kh.getTct());
            row.add(kh.getNgaySinh());
            model.addRow(row);
        }
        return model;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocXLS;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel controls;
    private com.toedter.calendar.JDateChooser dateChoser;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel header;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbHo;
    private javax.swing.JLabel lbMa;
    private javax.swing.JLabel lbNgaySinh;
    private javax.swing.JLabel lbPhai;
    private javax.swing.JLabel lbSdt;
    private javax.swing.JLabel lbTct;
    private javax.swing.JLabel lbTen;
    private javax.swing.JRadioButton option1;
    private javax.swing.JRadioButton option2;
    private javax.swing.ButtonGroup optionGroup;
    private javax.swing.ButtonGroup phaiGroup;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTable table;
    private javax.swing.JTextField textAmount;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textHo;
    private javax.swing.JTextField textMa;
    private javax.swing.JTextField textSdt;
    private javax.swing.JTextField textTct;
    private javax.swing.JTextField textTen;
    // End of variables declaration//GEN-END:variables
}
