
package GUI;
import BUS.ChiTietHoaDonBUS;
import BUS.ChiTietPhieuNhapBUS;
import BUS.NXBBUS;
import BUS.PhieuNhapBUS;
import BUS.SachBUS;
import BUS.TacGiaBUS;
import BUS.TheLoaiBUS;
import BUS.ValidatorBUS;
import DTO.SachDTO;
import DAO.SachDAO;
import DTO.ChiTietPhieuNhapDTO;
import DTO.NXBDTO;
import DTO.TacGiaDTO;
import DTO.TheLoaiDTO;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


public class QuanLySachGUI extends JPanel implements KeyListener {

    private int DEFALUT_WIDTH;
    private DefaultTableModel model;
    private ChiTietPhieuNhapBUS ctpnBUS =new ChiTietPhieuNhapBUS();
    private NXBBUS nxbBUS =new NXBBUS();
    private TacGiaBUS tgBUS =new TacGiaBUS();
    private TheLoaiBUS tlBUS =new TheLoaiBUS();
    private boolean EditorAdd;
    private BufferedImage i = null;//Hình ảnh chọn từ file
    private String imgName = "null";
    public QuanLySachGUI() {
        initComponents();
         this.setSize(1090, 750);
    }

    public QuanLySachGUI (int width) throws Exception
    {
        DEFALUT_WIDTH = width;
        initComponents();
       this.setSize(this.DEFALUT_WIDTH - 210, 950);
       InitVisible();
       ShowDataBase();
       LoadComboBox();
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        pThongKe = new javax.swing.JPanel();
        lbGiaMin = new javax.swing.JLabel();
        TongLoaiSoSach = new javax.swing.JLabel();
        txTongSoLoaiSach = new javax.swing.JTextField();
        txDonGiaMin = new javax.swing.JTextField();
        TongSoSach = new javax.swing.JLabel();
        txTongSoSach = new javax.swing.JTextField();
        lbGiaMax = new javax.swing.JLabel();
        txDonGiaMax = new javax.swing.JTextField();
        btThongKe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pInput = new javax.swing.JPanel();
        lbMaSach = new javax.swing.JLabel();
        lbMaNXB = new javax.swing.JLabel();
        lbMaTL = new javax.swing.JLabel();
        lbMaTG = new javax.swing.JLabel();
        lbTenSach = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbDonGia = new javax.swing.JLabel();
        cbMaTL = new javax.swing.JComboBox<>();
        cbMaTG = new javax.swing.JComboBox<>();
        txTenSach = new javax.swing.JTextField();
        txSoLuong = new javax.swing.JTextField();
        txDonGia = new javax.swing.JTextField();
        lnNamXuatBan = new javax.swing.JLabel();
        txNamXuatBan = new javax.swing.JTextField();
        cbMaNXB = new javax.swing.JComboBox<>();
        txMS = new javax.swing.JTextField();
        pButton = new javax.swing.JPanel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btXacNhan = new javax.swing.JButton();
        btQuayLai = new javax.swing.JButton();
        btChonAnh = new javax.swing.JButton();
        pSearch = new javax.swing.JPanel();
        lbSearchMaSach = new javax.swing.JLabel();
        lbSearchMaNXB = new javax.swing.JLabel();
        lbSearchMaTG = new javax.swing.JLabel();
        lbSearchTenSach = new javax.swing.JLabel();
        txSearchTenSach = new javax.swing.JTextField();
        btTimKiem = new javax.swing.JButton();
        cbSearchMaTG = new javax.swing.JComboBox<>();
        cbSearchMaTL = new javax.swing.JComboBox<>();
        lbSearchMATL = new javax.swing.JLabel();
        lbMin = new javax.swing.JLabel();
        txSearchMin = new javax.swing.JTextField();
        lbMax = new javax.swing.JLabel();
        txSearchMax = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lbSearchNamXuatBanMin = new javax.swing.JLabel();
        txSearchNamXuatBanMin = new javax.swing.JTextField();
        txSearchNamXuatBanMax = new javax.swing.JTextField();
        lbSearchNamXuatBanMax = new javax.swing.JLabel();
        cbSearchMaNXB = new javax.swing.JComboBox<>();
        txSearchMaSach = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pButton2 = new javax.swing.JPanel();
        btNhapExcel = new javax.swing.JButton();
        btXuatExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbImg = new javax.swing.JLabel();
        btHienThiTatCa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSach = new javax.swing.JTable();
        MaSach = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        pThongKe.setBackground(new java.awt.Color(255, 255, 255));

        lbGiaMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMin.setText("ĐƠN GIÁ THẤP NHẤT:");

        TongLoaiSoSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongLoaiSoSach.setText("SỐ LOẠI SÁCH:");

        txTongSoLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTongSoLoaiSachActionPerformed(evt);
            }
        });

        txDonGiaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDonGiaMinActionPerformed(evt);
            }
        });

        TongSoSach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        TongSoSach.setText("TỔNG SỐ SÁCH:");

        txTongSoSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTongSoSachActionPerformed(evt);
            }
        });

        lbGiaMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbGiaMax.setText("ĐƠN GIÁ CAO NHẤT:");

        txDonGiaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDonGiaMaxActionPerformed(evt);
            }
        });

        btThongKe.setBackground(new java.awt.Color(153, 255, 153));
        btThongKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bar_chart_30px.png"))); // NOI18N
        btThongKe.setText("THỐNG KÊ");
        btThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pThongKeLayout = new javax.swing.GroupLayout(pThongKe);
        pThongKe.setLayout(pThongKeLayout);
        pThongKeLayout.setHorizontalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongKeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbGiaMin)
                    .addComponent(TongLoaiSoSach, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txTongSoLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txDonGiaMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbGiaMax)
                    .addComponent(TongSoSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txTongSoSach, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(txDonGiaMax)))
        );
        pThongKeLayout.setVerticalGroup(
            pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pThongKeLayout.createSequentialGroup()
                .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pThongKeLayout.createSequentialGroup()
                        .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDonGiaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDonGiaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txTongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTongSoLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TongLoaiSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pThongKeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ SÁCH");

        pInput.setBackground(new java.awt.Color(255, 255, 255));

        lbMaSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaSach.setText("MÃ SÁCH:");

        lbMaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaNXB.setText("MÃ NXB:");

        lbMaTL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTL.setText("MÃ THỂ LOẠI:");

        lbMaTG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMaTG.setText("MÃ TÁC GIẢ:");

        lbTenSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTenSach.setText("TÊN SÁCH:");

        lbSoLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSoLuong.setText("SỐ LƯỢNG:");

        lbDonGia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDonGia.setText("ĐƠN GIÁ:");

        cbMaTL.addItem(" ");
        cbMaTL.addKeyListener(this);
        cbMaTL.setBackground(new java.awt.Color(243, 238, 238));
        cbMaTL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbMaTG.addItem(" ");
        cbMaTG.addKeyListener(this);
        cbMaTG.setBackground(new java.awt.Color(243, 238, 238));
        cbMaTG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txTenSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txSoLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txDonGia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lnNamXuatBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnNamXuatBan.setText("NĂM XUẤT BẢN:");

        txNamXuatBan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbMaNXB.setBackground(new java.awt.Color(243, 238, 238));
        cbMaNXB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbMaNXB.addItem(" ");
        MaSach.addKeyListener(this);
        cbMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMaNXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pInputLayout = new javax.swing.GroupLayout(pInput);
        pInput.setLayout(pInputLayout);
        pInputLayout.setHorizontalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbSoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbTenSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbMaTG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMaTL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbMaTL, 0, 223, Short.MAX_VALUE)
                            .addComponent(cbMaNXB, 0, 223, Short.MAX_VALUE)
                            .addComponent(txMS)))
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addComponent(lnNamXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(txNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pInputLayout.setVerticalGroup(
            pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pInputLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txMS, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pButton.setBackground(new java.awt.Color(255, 255, 255));
        pButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btThem.setBackground(new java.awt.Color(255, 255, 255));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnAdd_150px.png"))); // NOI18N
        btThem.setBorder(null);
        btThem.setContentAreaFilled(false);
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.setPreferredSize(new java.awt.Dimension(200, 43));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(255, 255, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 0, 0));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnEdit_150px.png"))); // NOI18N
        btSua.setBorder(null);
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.setPreferredSize(new java.awt.Dimension(57, 31));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(255, 255, 255));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 255, 255));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDelete_150px.png"))); // NOI18N
        btXoa.setBorder(null);
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btXacNhan.setBackground(new java.awt.Color(255, 255, 255));
        btXacNhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnConfirm_150px.png"))); // NOI18N
        btXacNhan.setBorder(null);
        btXacNhan.setContentAreaFilled(false);
        btXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXacNhan.setPreferredSize(new java.awt.Dimension(200, 43));
        btXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXacNhanActionPerformed(evt);
            }
        });

        btQuayLai.setBackground(new java.awt.Color(255, 102, 102));
        btQuayLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_undo_40px.png"))); // NOI18N
        btQuayLai.setText("QUAY LẠI");
        btQuayLai.setBorder(null);
        btQuayLai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btQuayLai.setPreferredSize(new java.awt.Dimension(57, 31));
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        btChonAnh.setBackground(new java.awt.Color(102, 102, 255));
        btChonAnh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btChonAnh.setForeground(new java.awt.Color(255, 255, 255));
        btChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_opened_folder_30px.png"))); // NOI18N
        btChonAnh.setText("CHỌN ẢNH");
        btChonAnh.setBorder(null);
        btChonAnh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButtonLayout = new javax.swing.GroupLayout(pButton);
        pButton.setLayout(pButtonLayout);
        pButtonLayout.setHorizontalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btQuayLai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        pButtonLayout.setVerticalGroup(
            pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pButtonLayout.createSequentialGroup()
                        .addComponent(btQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pButtonLayout.createSequentialGroup()
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pSearch.setBackground(new java.awt.Color(255, 255, 255));
        pSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)), "Tìm Kiếm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        lbSearchMaSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMaSach.setText("MÃ SÁCH:");

        lbSearchMaNXB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMaNXB.setText("MÃ NXB:");

        lbSearchMaTG.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMaTG.setText("MÃ TG:");

        lbSearchTenSach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchTenSach.setText("TÊN SÁCH:");

        txSearchTenSach.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btTimKiem.setBackground(new java.awt.Color(204, 204, 204));
        btTimKiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_25px_focus.png"))); // NOI18N
        btTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimKiemActionPerformed(evt);
            }
        });

        cbSearchMaTG.addItem("Không");
        cbSearchMaTG.setBackground(new java.awt.Color(243, 238, 238));
        cbSearchMaTG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbSearchMaTL.addItem("Không");
        cbSearchMaTL.setBackground(new java.awt.Color(243, 238, 238));
        cbSearchMaTL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbSearchMATL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbSearchMATL.setText("MÃ TL:");

        lbMin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMin.setText(" TỪ:");

        txSearchMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbMax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbMax.setText("ĐẾN:");

        txSearchMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("KHOẢNG GIÁ");

        lbSearchNamXuatBanMin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSearchNamXuatBanMin.setText("NĂM XB TỪ:");

        txSearchNamXuatBanMin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txSearchNamXuatBanMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSearchNamXuatBanMinActionPerformed(evt);
            }
        });

        txSearchNamXuatBanMax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txSearchNamXuatBanMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSearchNamXuatBanMaxActionPerformed(evt);
            }
        });

        lbSearchNamXuatBanMax.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbSearchNamXuatBanMax.setText("NĂM XB ĐẾN:");

        cbSearchMaNXB.addItem("Không");
        cbSearchMaNXB.setBackground(new java.awt.Color(243, 238, 238));
        cbSearchMaNXB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbSearchMaNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchMaNXBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSearchLayout = new javax.swing.GroupLayout(pSearch);
        pSearch.setLayout(pSearchLayout);
        pSearchLayout.setHorizontalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchMaNXB)
                        .addGap(14, 14, 14)
                        .addComponent(cbSearchMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchMaSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSearchMaSach)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSearchMaTG)
                    .addComponent(lbSearchMATL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbSearchMaTG, 0, 154, Short.MAX_VALUE)
                    .addComponent(cbSearchMaTL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchNamXuatBanMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSearchNamXuatBanMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSearchNamXuatBanMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSearchNamXuatBanMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbSearchTenSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSearchTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSearchLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(82, 82, 82))
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addComponent(lbMin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbMax)
                        .addGap(6, 6, 6)
                        .addComponent(txSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(btTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        pSearchLayout.setVerticalGroup(
            pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSearchLayout.createSequentialGroup()
                .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSearchLayout.createSequentialGroup()
                        .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSearchMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSearchMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(pSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSearchMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchMATL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSearchMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSearchMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchNamXuatBanMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchNamXuatBanMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSearchNamXuatBanMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchNamXuatBanMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchMin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txSearchMax, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btTimKiem))
                .addGap(6, 6, 6))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));

        pButton2.setBackground(new java.awt.Color(255, 255, 255));
        pButton2.setForeground(new java.awt.Color(255, 255, 255));

        btNhapExcel.setBackground(new java.awt.Color(255, 255, 153));
        btNhapExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btNhapExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ms_excel_30px.png"))); // NOI18N
        btNhapExcel.setText("NHẬP EXCEL");
        btNhapExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btNhapExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btNhapExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhapExcelActionPerformed(evt);
            }
        });

        btXuatExcel.setBackground(new java.awt.Color(204, 255, 204));
        btXuatExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btXuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_ms_excel_30px.png"))); // NOI18N
        btXuatExcel.setText("XUẤT EXCEL");
        btXuatExcel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btXuatExcel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXuatExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pButton2Layout = new javax.swing.GroupLayout(pButton2);
        pButton2.setLayout(pButton2Layout);
        pButton2Layout.setHorizontalGroup(
            pButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pButton2Layout.setVerticalGroup(
            pButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pButton2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btNhapExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbImg.setBackground(new java.awt.Color(102, 255, 102));
        lbImg.setForeground(new java.awt.Color(153, 153, 153));
        lbImg.setText("Ảnh");
        lbImg.setToolTipText("");
        lbImg.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 153)));
        lbImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImg, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        btHienThiTatCa.setBackground(new java.awt.Color(0, 153, 0));
        btHienThiTatCa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHienThiTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btHienThiTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_30px.png"))); // NOI18N
        btHienThiTatCa.setText("LÀM MỚI");
        btHienThiTatCa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHienThiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienThiTatCaActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbSach.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 51), new java.awt.Color(102, 102, 102)));
        tbSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ SÁCH", "MÃ NXB", "MÃ TL", "MÃ TG", "TÊN SÁCH", "NĂM XUẤT BẢN", "SỐ LƯỢNG", "ĐƠN GIÁ", "HÌNH ẢNH"
            }
        ));
        tbSach.setGridColor(new java.awt.Color(102, 102, 102));
        tbSach.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tbSach.setShowGrid(true);
        tbSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSach);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(949, 949, 949))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHienThiTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(pButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(781, 781, 781)
                .addComponent(MaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        EditorAdd=true;
        cleanView();

        btThem.setVisible(false);
        btSua.setVisible(false);
        btXoa.setVisible(false);

        btXacNhan.setVisible(true);
        btQuayLai.setVisible(true);
        btChonAnh.setVisible(true);

        tbSach.clearSelection();
        tbSach.setEnabled(false);
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        EditorAdd=false;

        btThem.setVisible(false);
        btSua.setVisible(false);
        btXoa.setVisible(false);

        btXacNhan.setVisible(true);
        btQuayLai.setVisible(true);
        btChonAnh.setVisible(true);
        
    }//GEN-LAST:event_btSuaActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int  i=tbSach.getSelectedRow();
        if (i>=0)
        {
            int k = JOptionPane.showConfirmDialog(null, "Bạn Thực Sự Muốn Xóa Sách Này ?","Thông Báo",JOptionPane.YES_NO_OPTION);
            if(k == 0){
                String idSach=txMS.getText();
                try {
                 /* ChiTietPhieuNhapBUS ctpnbus=new  ChiTietPhieuNhapBUS();
                    ctpnbus.deleteChiTietPhieuNhapByMaSach(idSach);
                  ChiTietHoaDonBUS cthdbus =new ChiTietHoaDonBUS();
                  cthdbus.deleteChiTietHoaDonByMaSach(idSach);*/
                  SachBUS bus =new SachBUS();
                  bus.deleteSach(idSach);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Sách Đang Được Xử Lý ở Hóa Đơn và Phiếu Nhập . Không Thể Xóa","Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
                }
                model.removeRow(i);
                tbSach.setModel(model);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXacNhanActionPerformed
        if(EditorAdd){
            try {
                // Validate
                StringBuilder sb =new StringBuilder();
                ValidatorBUS.checkEmpty(txMS, sb, "Mã Sách Còn Trống!");
                ValidatorBUS.checkEmpty(cbMaNXB, sb, "Mã Nhà Xuất Bản Còn Trống!");
                ValidatorBUS.checkEmpty(cbMaTG, sb, "Mã Tác Giả Còn Trống!");
                ValidatorBUS.checkEmpty(cbMaTL, sb, "Mã Thể Loại Còn Trống!");
                ValidatorBUS.checkEmpty(txTenSach, sb, "Tên Sách Còn Trống!");
                ValidatorBUS.checkEmpty(txNamXuatBan, sb, "Năm Xuất Bản Còn Trống !");
                ValidatorBUS.checkNumber(txNamXuatBan, sb, "Năm Xuất Bản là số !");
                ValidatorBUS.checkEmpty(txSoLuong, sb, "Số Lượng Còn Trống!");
                ValidatorBUS.checkNumber(txSoLuong, sb, "Số Lượng Là Số Nguyên !");
                ValidatorBUS.checkEmpty(txDonGia, sb, "Đơn Giá Còn Trống!");
                if(sb.length()>0){
                    JOptionPane.showMessageDialog(this,sb.toString(), "Thông Báo Lỗi Nhập",JOptionPane.ERROR_MESSAGE);
                    return ;
                }
                SachDTO sach=new SachDTO();
                sach.setMaSach((String)txMS.getText());
                sach.setMaNXB((String)cbMaNXB.getSelectedItem());
                sach.setMaTL((String)cbMaTL.getSelectedItem());
                sach.setMaTG((String)cbMaTG.getSelectedItem());
                sach.setTenSach(txTenSach.getText());
                sach.setNamXuatBan(Integer.parseInt(txNamXuatBan.getText()));
                sach.setSoluong(Integer.parseInt(txSoLuong.getText()));
                sach.setDongia(Float.parseFloat(txDonGia.getText()));
                sach.setImgName(imgName);// dể tam dể sau này thêm Ảnh ở đây
                SachBUS bus =new SachBUS();
                /* Kiem sao so luong co hop le hong
                ChiTietPhieuNhapBUS ctpnbus =new ChiTietPhieuNhapBUS();
                if(!ctpnbus.CheckSL(sach.getMaSach(), sach.getSoluong())) 
                    sach.setSoluong(ctpnbus.getSoLuong(sach.getMaSach()));
                /*Them sach len ke*/
                bus.addSach(sach);
                saveIMG();
                this.insertHeader();
                this.outModel(model,SachBUS.getListSach());

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Lỗi Thêm Sách ", "Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            int  i=tbSach.getSelectedRow();// i bắ t đầu từ 0
            if (i>=0)
            {
                try{
                    StringBuilder sb =new StringBuilder();
                    ValidatorBUS.checkEmpty(txMS, sb, "Mã Sách Còn Trống!");
                    ValidatorBUS.checkEmpty(cbMaNXB, sb, "Mã Nhà Xuất Bản Còn Trống!");
                    ValidatorBUS.checkEmpty(cbMaTG, sb, "Mã Tác Giả Còn Trống!");
                    ValidatorBUS.checkEmpty(cbMaTL, sb, "Mã Thể Loại Còn Trống!");
                    ValidatorBUS.checkEmpty(txTenSach, sb, "Tên Sách Còn Trống!");
                    ValidatorBUS.checkNumber(txNamXuatBan, sb, "Năm Xuất Bản Còn Trống !");
                    ValidatorBUS.checkNumber(txSoLuong, sb, "Số Lượng Là Số Nguyên !");
                    ValidatorBUS.checkEmpty(txDonGia, sb, "Đơn Giá Còn Trống!");
                    if(sb.length()>0){
                        JOptionPane.showMessageDialog(this,sb.toString(), "Thông Báo Lỗi Nhập",JOptionPane.ERROR_MESSAGE);
                        return ;
                    }

                    SachDTO sach=new SachDTO();
                    sach.setMaSach(txMS.getText().toString());
                    sach.setMaNXB(cbMaNXB.getSelectedItem().toString());
                    sach.setMaTL(cbMaTL.getSelectedItem().toString());
                    sach.setMaTG(cbMaTG.getSelectedItem().toString());
                    sach.setTenSach(txTenSach.getText());
                    sach.setNamXuatBan(Integer.parseInt(txNamXuatBan.getText()));
                    sach.setSoluong(Integer.parseInt(txSoLuong.getText()));
                    sach.setDongia(Float.parseFloat(txDonGia.getText()));
                    sach.setImgName(imgName);
                       /* Kiem sao so luong co hop le hong
                    ChiTietPhieuNhapBUS ctpnbus =new ChiTietPhieuNhapBUS();
                    if(!ctpnbus.CheckSL(sach.getMaSach(), sach.getSoluong())) 
                        sach.setSoluong(ctpnbus.getSoLuong(sach.getMaSach()));
                        /*Them sach len ke*/
                    SachBUS bus =new SachBUS();boolean check=true;
                    try {
                        bus.updateSach(sach);
                    } catch (Exception e) {
                        check=false;
                        JOptionPane.showMessageDialog(this,"Không Thể Sửa Mã Sách", "Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
                    }
                    if(check){
                        model.setValueAt(sach.getMaSach(), i, 0);
                        model.setValueAt(sach.getMaNXB(), i, 1);
                        model.setValueAt(sach.getMaTL(), i, 2);
                        model.setValueAt(sach.getMaTG(), i, 3);
                        model.setValueAt(sach.getTenSach(), i, 4);
                        model.setValueAt(sach.getNamXuatBan(), i, 5);
                        model.setValueAt(sach.getSoluong(), i, 6);
                        model.setValueAt(sach.getDongia(), i, 7);
                        model.setValueAt(sach.getImgName(), i, 8);}
                    tbSach.setModel(model);
                    saveIMG();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Không Thể Sửa Sách", "Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
                }
            }

        }
    }//GEN-LAST:event_btXacNhanActionPerformed

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        cleanView();
        btThem.setVisible(true);
        btSua.setVisible(true);
        btXoa.setVisible(true);

        btXacNhan.setVisible(false);
        btQuayLai.setVisible(false);
        btChonAnh.setVisible(false);

        tbSach.setEnabled(true);
    }//GEN-LAST:event_btQuayLaiActionPerformed

    private void btChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonAnhActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PNG imgs", "jpg", "png");
        fc.setFileFilter(filter);
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            try {
                File file = fc.getSelectedFile(); //Lấy URL hình
                this.i = ImageIO.read(file); // Lấy hình
                imgName = txMS.getText().concat(".jpg"); //Tên hình
                // Thay đổi hình hiển thị
                lbImg.setText("");
                lbImg.setIcon(new ImageIcon(i.getScaledInstance(200, 230, Image.SCALE_DEFAULT)));
                revalidate();
                repaint();
            } catch (IOException ex) {
                Logger.getLogger(QuanLySachGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btChonAnhActionPerformed

    private void btHienThiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienThiTatCaActionPerformed
        tbSach.setModel(model);
    }//GEN-LAST:event_btHienThiTatCaActionPerformed

    private void btTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimKiemActionPerformed
        Search();
    }//GEN-LAST:event_btTimKiemActionPerformed

    private void txSearchNamXuatBanMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSearchNamXuatBanMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSearchNamXuatBanMinActionPerformed

    private void tbSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachMouseClicked

        int i = tbSach.getSelectedRow();
        if(i>=0)
        {
            if(tbSach.getRowSorter() != null)
            {
                i = tbSach.getRowSorter().convertRowIndexToModel(i);
            }
            imgName = tbSach.getModel().getValueAt(i, 8).toString();
            Image newImage ;
            try{
                newImage = new ImageIcon("./src/img/SanPham/"+imgName).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            }catch(NullPointerException E)
            {
                newImage = new ImageIcon("./src/img/SanPham/NoImage.jpg").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT);
            }

            txMS.setText(tbSach.getModel().getValueAt(i, 0).toString());
            cbMaNXB.setSelectedItem(nxbBUS.searchMaNXB(tbSach.getModel().getValueAt(i, 1).toString()).getMaNXB());
            cbMaTL.setSelectedItem(tlBUS.searchMaTL(tbSach.getModel().getValueAt(i, 2).toString()).getMaTL());
            cbMaTG.setSelectedItem(tgBUS.searchMaTG(tbSach.getModel().getValueAt(i, 3).toString()).getMaTG());
            txTenSach.setText( tbSach.getModel().getValueAt(i, 4).toString());
            txNamXuatBan.setText( tbSach.getModel().getValueAt(i, 5).toString());
            txSoLuong.setText( tbSach.getModel().getValueAt(i, 6).toString());
            txDonGia.setText( tbSach.getModel().getValueAt(i, 7).toString());
            lbImg.setText("");
            lbImg.setIcon(new ImageIcon(newImage));

        }
    }//GEN-LAST:event_tbSachMouseClicked

    private void txSearchNamXuatBanMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSearchNamXuatBanMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSearchNamXuatBanMaxActionPerformed

    private void txDonGiaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDonGiaMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaMinActionPerformed

    private void txTongSoLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTongSoLoaiSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTongSoLoaiSachActionPerformed

    private void btThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThongKeActionPerformed
       SachBUS bus =new SachBUS();
       tbSach.setModel(model);
       lbGiaMin.setVisible(true);lbGiaMax.setVisible(true);
       txDonGiaMin.setVisible(true);txDonGiaMax.setVisible(true);
        txDonGiaMin.setText(String.valueOf(bus.DonGiaMin()) );
        txDonGiaMax.setText(String.valueOf(bus.DonGiaMax()) );
        txTongSoSach.setText(String.valueOf(bus.TongSoSach()) );
        txTongSoLoaiSach.setText(String.valueOf(bus.getLengthListSach()) );
    }//GEN-LAST:event_btThongKeActionPerformed

    private void txTongSoSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTongSoSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTongSoSachActionPerformed

    private void txDonGiaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDonGiaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDonGiaMaxActionPerformed

    private void btXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXuatExcelActionPerformed
        SachBUS bus =new SachBUS();
        try {
            bus.ExportExcelDatabase();
            //JOptionPane.showMessageDialog(null, "Xuất file excel thành công");     
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, "Xuất file excel thất bại");     
        }
    }//GEN-LAST:event_btXuatExcelActionPerformed

    private void btNhapExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhapExcelActionPerformed
       JFileChooser fc = new JFileChooser();
                FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Excel", "xlsx");
                fc.setFileFilter(filter);
                SachBUS bus =new SachBUS();
                int result = fc.showOpenDialog(null);
                if (result == JFileChooser.APPROVE_OPTION) 
                {
                    File file = fc.getSelectedFile(); //Lấy URL
           try {
               bus.ImportExcelDatabase(file);
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Import file excel thất bại"); 
           }
           try {
               bus.loadDSSach();
           } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Xuất file excel ra table thất bại"); 
           }
                    outModel(model, bus.getlistSach());
                    JOptionPane.showMessageDialog(null, "Nhap file excel thanh cong");
                }
    }//GEN-LAST:event_btNhapExcelActionPerformed

    private void cbMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMaNXBActionPerformed

    private void cbSearchMaNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchMaNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSearchMaNXBActionPerformed
    private void InitVisible(){
        lbImg.setIcon(new ImageIcon("./src/img/profile01-250px.png"));
                btXacNhan.setVisible(false);
                btQuayLai.setVisible(false);
                btChonAnh.setVisible(false);
    }
    private void insertHeader(){
        Vector header = new Vector();
        header.add("MÃ SÁCH");
        header.add("MÃ NXB");
        header.add("MÃ THỂ LOẠI");
        header.add("MÃ TÁC GIẢ");
        header.add("TÊN SÁCH");
        header.add("NĂM XUẤT BẢN");
        header.add("SỐ LƯỢNG");
        header.add("ĐƠN GIÁ");
        header.add("HÌNH ẢNH");
        //if (model.getRowCount()==0)
              model=new DefaultTableModel(header,0);
              
           
    }
    private void outModel(DefaultTableModel model ,ArrayList<SachDTO> sach) // Xuất ra Table từ ArrayList
    {
        Vector data;
        model.setRowCount(0);
        for(SachDTO s: sach)
        {
            data = new Vector();
            data.add(s.getMaSach());
            data.add(s.getMaNXB());
            data.add(s.getMaTL());
            data.add(s.getMaTG());
            data.add(s.getTenSach());
            data.add(s.getNamXuatBan());
            data.add(s.getSoluong());
            data.add(s.getDongia());
            data.add(s.getImgName());
            model.addRow(data);
        }
        tbSach.setModel(model);
    }

    private void ShowDataBase() throws Exception{       
        try {
            SachBUS bus =new SachBUS();
        if(SachBUS.getListSach()==null) bus.loadDSSach();
        insertHeader();
        outModel(model,SachBUS.getListSach());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Không Thể Load Database ", "Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    private void cleanView(){
        txMS.setText("");
        cbMaNXB.setSelectedItem("");
        cbMaTG.setSelectedItem("");
        cbMaTL.setSelectedItem("");
        txTenSach.setText("");
        txNamXuatBan.setText("");
        txSoLuong.setText("");
        txDonGia.setText("");
        lbImg.setIcon(null);
        lbImg.setText(imgName);
        
        imgName = "null";

    }
    private void Search(){
         DefaultTableModel temp=new DefaultTableModel();
         ArrayList<SachDTO> search=new ArrayList<>();
         int tongsosach=0;
         Vector header = new Vector();
        header.add("MÃ SÁCH");//tua de cot cua jtable
        header.add("MÃ NXB");
        header.add("MÃ THỂ LOẠI");
        header.add("MÃ TÁC GIẢ");//tua de cot cua jtable
        header.add("TÊN SÁCH");
        header.add("NĂM XUẤT BẢN");
        header.add("SỐ LƯỢNG");
        header.add("ĐƠN GIÁ");
        header.add("HÌNH ẢNH");
       
        try {
            SachBUS bus =new SachBUS();
            int namxbmin = txSearchNamXuatBanMin.getText().equals("") ? 1000: Integer.parseInt(txSearchNamXuatBanMin.getText()); 
            int namxbmax = txSearchNamXuatBanMax.getText().equals("") ? 4000: Integer.parseInt(txSearchNamXuatBanMax.getText()); 
            float min = txSearchMin.getText().equals("") ? 0 : Float.parseFloat(txSearchMin.getText());
            float max = txSearchMax.getText().equals("") ? 999999: Float.parseFloat(txSearchMax.getText());    
            search=bus.searchSach(txSearchMaSach.getText(),
                    cbSearchMaNXB.getSelectedItem().toString(),
                    cbSearchMaTG.getSelectedItem().toString(), 
                    cbSearchMaTL.getSelectedItem().toString(), 
                    txSearchTenSach.getText(),namxbmin,namxbmax,min,max);
          System.out.println(txSearchMaSach.getText()+" "+cbSearchMaNXB.getSelectedItem().toString()+" "+cbSearchMaTG.getSelectedItem().toString()+" "+namxbmin+" --- "+txSearchTenSach.getText() +" "+min+" -- "+max);
        } catch (Exception e) {
         JOptionPane.showMessageDialog(this,"Không Thể Tìm Kiếm ", "Thông Báo Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        if(search != null && search.size() > 0) {
           // outModel(temp,search);
           if (temp.getRowCount()==0)
                    {temp=new DefaultTableModel(header,0);}
            for(int i=0;i<search.size();i++){
                 Vector row=new Vector();
                    row.add(search.get(i).getMaSach());
                    row.add(search.get(i).getMaNXB());
                    row.add(search.get(i).getMaTL());
                    row.add(search.get(i).getMaTG());
                    row.add(search.get(i).getTenSach());
                    row.add(search.get(i).getNamXuatBan());
                    row.add(search.get(i).getSoluong());
                    row.add(search.get(i).getDongia());
                    row.add(search.get(i).getImgName());        
                 temp.addRow(row);
            }
        }
        for(SachDTO s:search){
            tongsosach+=s.getSoluong();
        }
        tbSach.setModel(temp);
         lbGiaMin.setVisible(false);lbGiaMax.setVisible(false);
        txDonGiaMin.setVisible(false);txDonGiaMax.setVisible(false);
        txTongSoSach.setText(String.valueOf(tongsosach) );
        txTongSoLoaiSach.setText(String.valueOf(search.size()) );
        
    }
    public void saveIMG()
    {
        try {
            if(this.i != null)
            {
                File save = new File("src/img/SanPham/"+ imgName);//Tạo file
                ImageIO.write(i,"jpg",save); // Lưu hình i vào đường dẫn file save

                this.i = null; //Xóa hình trong bộ nhớ 
            }
        } catch (IOException ex) {
            Logger.getLogger(QuanLySachGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    public void LoadComboBox() throws Exception{
        listNXB(cbMaNXB);
        listTG(cbMaTG);
        listTL(cbMaTL);
        listNXB(cbSearchMaNXB);
        listTG(cbSearchMaTG);
        listTL(cbSearchMaTL);
       
        
    }
    public void listNXB(JComboBox cmb) throws Exception
    {
        if(nxbBUS.getlistNXB()== null) nxbBUS.loadDSNXB();
        ArrayList<NXBDTO> nxb = nxbBUS.getlistNXB();
        for(NXBDTO a : nxb){
            cmb.addItem(a.getMaNXB());
        }
      
    }
    public void listTL(JComboBox cmb) throws Exception
    {
        if(tlBUS.getListTheLoai()== null) tlBUS.loadDSTheLoai();
        ArrayList<TheLoaiDTO> tl = tlBUS.getListTheLoai();
        for(TheLoaiDTO a : tl){
            cmb.addItem(a.getMaTL());
        }
      
    }
    public void listTG(JComboBox cmb) throws Exception
    {
        if(tgBUS.getListTacGia()== null) tgBUS.loadDSTacGia();
        ArrayList<TacGiaDTO> tg = tgBUS.getListTacGia();
        for(TacGiaDTO  a: tg){
            cmb.addItem(a.getMaTG());
        }
      
    }
   
    public void addCombo(JComboBox cmb,ArrayList<Object> list)
    {
        for(Object a:list)
        {
            cmb.addItem(a);
            
        }
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MaSach;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel TongLoaiSoSach;
    private javax.swing.JLabel TongSoSach;
    private javax.swing.JButton btChonAnh;
    private javax.swing.JButton btHienThiTatCa;
    private javax.swing.JButton btNhapExcel;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton btTimKiem;
    private javax.swing.JButton btXacNhan;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXuatExcel;
    private javax.swing.JComboBox<String> cbMaNXB;
    private javax.swing.JComboBox<String> cbMaTG;
    private javax.swing.JComboBox<String> cbMaTL;
    private javax.swing.JComboBox<String> cbSearchMaNXB;
    private javax.swing.JComboBox<String> cbSearchMaTG;
    private javax.swing.JComboBox<String> cbSearchMaTL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbGiaMax;
    private javax.swing.JLabel lbGiaMin;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbMaNXB;
    private javax.swing.JLabel lbMaSach;
    private javax.swing.JLabel lbMaTG;
    private javax.swing.JLabel lbMaTL;
    private javax.swing.JLabel lbMax;
    private javax.swing.JLabel lbMin;
    private javax.swing.JLabel lbSearchMATL;
    private javax.swing.JLabel lbSearchMaNXB;
    private javax.swing.JLabel lbSearchMaSach;
    private javax.swing.JLabel lbSearchMaTG;
    private javax.swing.JLabel lbSearchNamXuatBanMax;
    private javax.swing.JLabel lbSearchNamXuatBanMin;
    private javax.swing.JLabel lbSearchTenSach;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JLabel lnNamXuatBan;
    private javax.swing.JPanel pButton;
    private javax.swing.JPanel pButton2;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pSearch;
    private javax.swing.JPanel pThongKe;
    private javax.swing.JTable tbSach;
    private javax.swing.JTextField txDonGia;
    private javax.swing.JTextField txDonGiaMax;
    private javax.swing.JTextField txDonGiaMin;
    private javax.swing.JTextField txMS;
    private javax.swing.JTextField txNamXuatBan;
    private javax.swing.JTextField txSearchMaSach;
    private javax.swing.JTextField txSearchMax;
    private javax.swing.JTextField txSearchMin;
    private javax.swing.JTextField txSearchNamXuatBanMax;
    private javax.swing.JTextField txSearchNamXuatBanMin;
    private javax.swing.JTextField txSearchTenSach;
    private javax.swing.JTextField txSoLuong;
    private javax.swing.JTextField txTenSach;
    private javax.swing.JTextField txTongSoLoaiSach;
    private javax.swing.JTextField txTongSoSach;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent e) {
       Object a = e.getSource();
       /* if(a.equals(cbSearchMaTG) || a.equals(cbSearchMaTL) || a.equals(txSearchMaSach) || a.equals(txSearchMaSach.getText()) 
                || a.equals(txSearchTenSach) || a.equals(txSearchMin) || a.equals(txSearchMax)
                || a.equals(txSearchNamXuatBanMin) || a.equals(txSearchMin) )
        {*/
            if(e.getKeyCode() == KeyEvent.VK_ENTER)
            {
                Search();
            }
       /* }   */ }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
